package exception_handling;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;

public class CombinationOfTryCatchFinally {

	public static void main(String[] args) {
try {
	
}catch(NullPointerException e) {
	
}
try {
	
}catch(RuntimeException f) {
	
}
try {
	
}catch(Error g){
	
}
try {
	
}catch(Exception h) {
	
}
try {
	
}catch(Throwable i) {
	
}
//try {
//	
//}catch(FileNotFoundException j) {
//	
//}
//multiple catch block
try {
	
}catch(RuntimeException k) {
	
}
catch(Exception l) {
	
}
//try {
//	
//}catch(NullPointerException m) {
//	
//}
//catch(NullPointerException n) {
//	
//}
//try {
//	
//}catch(RuntimeException o) {
//	
//}catch(NullPointerException p) {
//	
//}
try {
	
}catch(NullPointerException o) {
	
}catch(RuntimeException p) {
	
}
//try catch finally cobination .

try {
	
}
catch(Exception e) {
	
}
finally {
	
}
//try {
//	
//}finally {
//	
//}catch(Exception e) {
//	
//}
try {
	
}finally {
	
}
//try {
//	
//}finally {
//	
//}finally {
//	
//}
	try {
		System.out.println( 10/0);
		File file=new File("C:\\Users\\ADMIN\\OneDrive\\Documents\\New folder\\Hello.txt");
		file.createNewFile();
		throw new FileNotFoundException();
	} catch(ArithmeticException d){
		
	}
	catch(FileNotFoundException e) {
		
	}catch(IOException f) {
		
	}
	try {
		System.out.println( 10/0);
		File file=new File("C:\\Users\\ADMIN\\OneDrive\\Documents\\New folder\\Hello.txt");
		file.createNewFile();
		throw new FileNotFoundException();
	} catch(ArithmeticException |FileNotFoundException d){
		
	}
	catch(IOException f) {
		
	}
	}
	}